#!/bin/sh -x

EXTRA_FLAGS="-Wall -pedantic -std=gnu99"
export CFLAGS="`llvm-config --cflags` $EXTRA_FLAGS"

MZC_CPP=""
for f in `llvm-config --cppflags` $EXTRA_FLAGS; do
    MZC_CPP="${MZC_CPP}++cppf $f "
done

mzc --3m --vv --xform $MZC_CPP llvm-basic.c && \
mzc --3m --vv --cc llvm-basic.3m.c && \
mzc --3m --ld llvm-basic.so llvm-basic_3m.o -- `llvm-config --ldflags` -lstdc++ `llvm-config --libfiles engine backend bitreader bitwriter`
